### PR TITLE
React Native new architecture support

### PR DESCRIPTION
**Pull request by BrunoVillanova**
Add library and Example app support for RN new architecture.

### CODE REVIEW

**Comment by k-saparia** [comment]
Hey, please release a new version with new architecture support asap. Really excited to integrate in my project! Thanks!!

**Comment by affansk** [comment]
@agoldis  Just want to check on this. in future are you going to merge this PR

**Comment by BrunoVillanova** [comment]
I will fix the PR conflicts.

**Comment by BrunoVillanova** [comment]
Awesome.
Thank you Andrew!

Bruno Villanova
***@***.*** |
Digimundi |
BR

**Pull request merged**
